#!/bin/bash

echo "🚀 Fresh droplet setup instructions"
echo ""
echo "1. Create new droplet or reset current one"
echo "2. Run ONLY these commands:"
echo "   - git clone your-repo"
echo "   - Install Node.js 20, pnpm, PM2"
echo "   - pnpm install && pnpm build"
echo "   - Setup basic nginx (HTTP only)"
echo "   - pm2 start ecosystem.config.js"
echo ""
echo "3. Test HTTP first before adding HTTPS"
echo "4. Once working, add HTTPS gradually"
echo ""
echo "DO NOT run setup-droplet.sh - it breaks the working setup"
