#!/bin/bash

echo "📦 Monorepo split strategy"
echo ""
echo "Frontend (Next.js):"
echo "- Deploy to Vercel/Netlify (handles HTTPS automatically)"
echo "- Point to api.questly.me for backend"
echo ""
echo "Backend (Express):"
echo "- Keep on DigitalOcean droplet"
echo "- Simple nginx config for api.questly.me"
echo "- Much easier to manage"
echo ""
echo "Benefits:"
echo "- Frontend gets CDN, edge functions, auto-HTTPS"
echo "- Backend stays simple"
echo "- No proxy complications"
echo ""
echo "Drawbacks:"
echo "- Separate deployments"
echo "- CORS configuration needed"
