export type Achievement = {
  id: string;
  name: string;
  description: string;
  icon: string; // icon name or url
  category: string;
  importance: "common" | "rare" | "epic" | "legendary";
  criteria: {
    type: string; // e.g. 'quest_completed', 'xp_earned', 'streak', etc.
    value: number;
    [key: string]: any;
  };
  hidden?: boolean; // for secret achievements
};

export const ACHIEVEMENTS: Achievement[] = [
  // First Steps & Milestones
  {
    id: "first_quest",
    name: "The First Step",
    description: "Complete your very first quest.",
    icon: "star",
    category: "Milestone",
    importance: "common",
    criteria: { type: "quest_completed", value: 1 },
  },
  {
    id: "add_first_quest",
    name: "Eager Explorer",
    description: "Add your very first quest.",
    icon: "star",
    category: "Milestone",
    importance: "common",
    criteria: { type: "quest_added", value: 1 },
  },
  {
    id: "add_first_main_quest",
    name: "Adventure Spirit",
    description: "Add your very first main quest.",
    icon: "crown",
    category: "Milestone",
    importance: "common",
    criteria: { type: "main_quest_added", value: 1 },
  },

  // Quest Completion Achievements
  {
    id: "quest_novice",
    name: "Rookie Adventurer",
    description: "Complete 10 quests.",
    icon: "medal",
    category: "Quest Completion",
    importance: "common",
    criteria: { type: "quest_completed", value: 10 },
  },
  {
    id: "quest_apprentice",
    name: "Seasoned Explorer",
    description: "Complete 25 quests.",
    icon: "medal",
    category: "Quest Completion",
    importance: "common",
    criteria: { type: "quest_completed", value: 25 },
  },
  {
    id: "quest_veteran",
    name: "Veteran Adventurer",
    description: "Complete 50 quests.",
    icon: "trophy",
    category: "Quest Completion",
    importance: "rare",
    criteria: { type: "quest_completed", value: 50 },
  },
  {
    id: "quest_master",
    name: "Legend of the Land",
    description: "Complete 100 quests.",
    icon: "trophy",
    category: "Quest Completion",
    importance: "epic",
    criteria: { type: "quest_completed", value: 100 },
  },
  {
    id: "quest_grandmaster",
    name: "Eternal Champion",
    description: "Complete 250 quests.",
    icon: "crown",
    category: "Quest Completion",
    importance: "legendary",
    criteria: { type: "quest_completed", value: 250 },
  },

  // XP Achievements
  {
    id: "xp_1000",
    name: "Spark of Power",
    description: "Earn 1,000 XP.",
    icon: "zap",
    category: "Experience",
    importance: "common",
    criteria: { type: "xp_earned", value: 1000 },
  },
  {
    id: "xp_5000",
    name: "Rising Star",
    description: "Earn 5,000 XP.",
    icon: "zap",
    category: "Experience",
    importance: "common",
    criteria: { type: "xp_earned", value: 5000 },
  },
  {
    id: "xp_15000",
    name: "Power Surge",
    description: "Earn 15,000 XP.",
    icon: "zap",
    category: "Experience",
    importance: "rare",
    criteria: { type: "xp_earned", value: 15000 },
  },
  {
    id: "xp_50000",
    name: "True Adventurer",
    description: "Earn 50,000 XP.",
    icon: "zap",
    category: "Experience",
    importance: "rare",
    criteria: { type: "xp_earned", value: 50000 },
  },
  {
    id: "xp_100000",
    name: "Aura Farmer",
    description: "Earn 100,000 XP.",
    icon: "zap",
    category: "Experience",
    importance: "epic",
    criteria: { type: "xp_earned", value: 100000 },
  },
  {
    id: "xp_250000",
    name: "Mythic Soul",
    description: "Earn 250,000 XP.",
    icon: "zap",
    category: "Experience",
    importance: "epic",
    criteria: { type: "xp_earned", value: 250000 },
  },
  {
    id: "xp_500000",
    name: "Ascended Being",
    description: "Earn 500,000 XP.",
    icon: "gem",
    category: "Experience",
    importance: "legendary",
    criteria: { type: "xp_earned", value: 500000 },
  },
  {
    id: "xp_1000000",
    name: "Titan of Triumph",
    description: "Earn 1,000,000 XP.",
    icon: "crown",
    category: "Experience",
    importance: "legendary",
    criteria: { type: "xp_earned", value: 1000000 },
  },

  // Streak Achievements
  {
    id: "streak_3",
    name: "Kindling the Flame",
    description: "Maintain a 3-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "common",
    criteria: { type: "streak", value: 3 },
  },
  {
    id: "streak_7",
    name: "Unbroken Chain",
    description: "Maintain a 7-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "common",
    criteria: { type: "streak", value: 7 },
  },
  {
    id: "streak_14",
    name: "Fortnight Warrior",
    description: "Maintain a 14-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "rare",
    criteria: { type: "streak", value: 14 },
  },
  {
    id: "streak_30",
    name: "Monthly Master",
    description: "Maintain a 30-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "rare",
    criteria: { type: "streak", value: 30 },
  },
  {
    id: "streak_60",
    name: "Unstoppable Force",
    description: "Maintain a 60-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "epic",
    criteria: { type: "streak", value: 60 },
  },
  {
    id: "streak_100",
    name: "Century of Dedication",
    description: "Maintain a 100-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "epic",
    criteria: { type: "streak", value: 100 },
  },
  {
    id: "streak_365",
    name: "Year of the Phoenix",
    description: "Maintain a 365-day streak.",
    icon: "flame",
    category: "Consistency",
    importance: "legendary",
    criteria: { type: "streak", value: 365 },
  },

  // Side Quest Achievements
  {
    id: "side_quester",
    name: "Wanderer's Spirit",
    description: "Complete 5 side quests.",
    icon: "compass",
    category: "Side Quest",
    importance: "common",
    criteria: { type: "side_quest_completed", value: 5 },
  },
  {
    id: "side_quest_explorer",
    name: "Path Less Traveled",
    description: "Complete 15 side quests.",
    icon: "compass",
    category: "Side Quest",
    importance: "rare",
    criteria: { type: "side_quest_completed", value: 15 },
  },
  {
    id: "side_quest_master",
    name: "Master of Detours",
    description: "Complete 50 side quests.",
    icon: "compass",
    category: "Side Quest",
    importance: "epic",
    criteria: { type: "side_quest_completed", value: 50 },
  },

  // Main Quest Achievements
  {
    id: "main_quest_hero",
    name: "Destined Hero",
    description: "Complete your first main quest.",
    icon: "shield",
    category: "Main Quest",
    importance: "rare",
    criteria: { type: "main_quest_completed", value: 1 },
  },
  {
    id: "main_quest_champion",
    name: "Champion of Destiny",
    description: "Complete 5 main quests.",
    icon: "shield",
    category: "Main Quest",
    importance: "epic",
    criteria: { type: "main_quest_completed", value: 5 },
  },
  {
    id: "main_quest_legend",
    name: "Legendary Hero",
    description: "Complete 10 main quests.",
    icon: "crown",
    category: "Main Quest",
    importance: "legendary",
    criteria: { type: "main_quest_completed", value: 10 },
  },

  // Task Achievements
  {
    id: "task_starter",
    name: "Getting Things Done",
    description: "Complete 10 tasks.",
    icon: "check-circle",
    category: "Productivity",
    importance: "common",
    criteria: { type: "task_completed", value: 10 },
  },
  {
    id: "task_worker",
    name: "Busy Bee",
    description: "Complete 25 tasks.",
    icon: "check-circle",
    category: "Productivity",
    importance: "common",
    criteria: { type: "task_completed", value: 25 },
  },
  {
    id: "taskmaster",
    name: "Taskmaster",
    description: "Complete 50 tasks.",
    icon: "check-circle",
    category: "Productivity",
    importance: "rare",
    criteria: { type: "task_completed", value: 50 },
  },
  {
    id: "task_machine",
    name: "Productivity Machine",
    description: "Complete 100 tasks.",
    icon: "check-circle",
    category: "Productivity",
    importance: "rare",
    criteria: { type: "task_completed", value: 100 },
  },
  {
    id: "task_legend",
    name: "Master of Efficiency",
    description: "Complete 250 tasks.",
    icon: "gem",
    category: "Productivity",
    importance: "epic",
    criteria: { type: "task_completed", value: 250 },
  },

  // Special/Hidden Achievements
  {
    id: "early_bird",
    name: "Early Bird",
    description: "Complete a quest before 6 AM.",
    icon: "star",
    category: "Special",
    importance: "rare",
    criteria: { type: "early_completion", value: 1 },
    hidden: true,
  },
  {
    id: "night_owl",
    name: "Night Owl",
    description: "Complete a quest after 11 PM.",
    icon: "star",
    category: "Special",
    importance: "rare",
    criteria: { type: "late_completion", value: 1 },
    hidden: true,
  },
  {
    id: "perfectionist",
    name: "Perfectionist",
    description: "Complete all daily quests for 7 days straight.",
    icon: "gem",
    category: "Special",
    importance: "epic",
    criteria: { type: "perfect_week", value: 1 },
    hidden: true,
  },
];
