import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  EB_Garamond,
  MedievalSharp,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/components/query-provider";
import PullToRefresh from "@/components/pull-to-refresh";
import { SidebarProvider } from "@/contexts/sidebar-context";
import { AnonymousLoginProvider } from "@/components/anonymous-login-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});
const medievalSharp = MedievalSharp({
  variable: "--font-medieval",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  style: "normal",
  fallback: ["cursive"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ebGaramond.variable} font-garamond antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <AnonymousLoginProvider>
              <SidebarProvider>
                <PullToRefresh />
                {children}
              </SidebarProvider>
            </AnonymousLoginProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
