version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-questly}
      POSTGRES_USER: ${POSTGRES_USER:-questly}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=peer"
    ports:
      - "127.0.0.1:5432:5432" # Only bind to localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../configs/postgresql.conf:/etc/postgresql/postgresql.conf
      - ../configs/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ../configs/init-scripts:/docker-entrypoint-initdb.d
    command: >
      postgres 
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-questly} -d ${POSTGRES_DB:-questly}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    image: ${API_IMAGE:-ghcr.io/vinayak-00017/questly-api:latest}
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ../../.env.production
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://${POSTGRES_USER:-questly}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-questly}
    depends_on:
      - postgres
    networks:
      - app-network

  web:
    image: ${WEB_IMAGE:-ghcr.io/vinayak-00017/questly-web:latest}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.production
    environment:
      NODE_ENV: production
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/nginx.conf
      - ../configs/ssl:/etc/ssl/certs
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - api
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
    internal: false
