version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-questly}
      POSTGRES_USER: ${POSTGRES_USER:-questly}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password_change_me}
    # No external port binding - only accessible from other containers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    image: ${API_IMAGE:-ghcr.io/vinayak-00017/questly-api:latest}
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ../../.env.production
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://${POSTGRES_USER:-questly}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-questly}
    depends_on:
      - postgres
    networks:
      - app-network

  web:
    image: ${WEB_IMAGE:-ghcr.io/vinayak-00017/questly-web:latest}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.production
    environment:
      NODE_ENV: production
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/nginx.conf
      - ../configs/ssl:/etc/ssl/certs
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - api
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
    internal: false
